name: Tag and build docker image

on:
  pull_request:
    types:
    - closed

jobs:
  check_labels:
    name: Check Build Label
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      labels: steps.pr-labels.outputs.labels
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      - name: Check pr merged
        run: echo "${{ github.event.pull_request.merged }}"
      - name: Check label contains
        run: echo "${{ contains(steps.pr-labels.outputs.labels, 'build-docker') }}"
      - name: Echo label
        run: echo "${{ steps.pr-labels.outputs.labels }}"
      - name: Full check
        run: echo "${{ (github.event.pull_request.merged == true) && (contains(needs.pr-labels.outputs.labels, 'build-docker')) }}"
  push_to_registry:
    name: Push Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs:
      - check_labels
    if: ${{ (github.event.pull_request.merged == true) && (contains(needs.check_labels.outputs.labels, 'build-docker')) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Get github hash
        id: github-hash
        run: echo "github_hash=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/eastbay:latest,registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/eastbay:${{ steps.github-hash.outputs.github_hash }}
