name: Tag and build docker image

on:
  pull_request:
    types:
    - closed

jobs:
  push_to_registry:
    name: Push Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@e61c643fe47e53d3495405cc9f441b5da06ab1e9
      - name: Check labels
        if: ${{ !(contains(steps.pr-labels.outputs.labels, 'build-docker')) }}
        run: exit 0
      - name: Check out the repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        if: contains(steps.pr-labels.outputs.labels, 'build-docker')
      - name: Install doctl
        uses: digitalocean/action-doctl@0e7c88a2988e3a39f018289c5a1b90d460a62ffc
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Get github hash
        id: github-hash
        run: echo "github_hash=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@84ad562665bb303b549fec655d1b64f9945f3f91
        with:
          push: true
          context: .
          tags: registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/eastbay:latest,registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/eastbay:${{ steps.github-hash.outputs.github_hash }}
